# Generated by Django 4.2.5 on 2024-02-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
